### ISSUE TITLE
Download to external storage fails

### ISSUE THREAD

**Issue by omarbelkhodja** [BiglySoftware/BiglyBT-Android#159]
I'm using BiglyBt on Android TV. I'm adding torrents from my phone (using the remote feature of BiglyBT). When I configure BiglyBT for saving file on an external USB Disk, I have the following error 👍 

```
2020-08-09 19:19:56.907 757-2192/com.biglybt.android.client E/System: DEBUG::Sun Aug 09 19:19:56 GMT+01:00 2020::com.biglybt.core.disk.impl.DiskManagerImpl::filesExist::894:
2020-08-09 19:19:56.908 757-2192/com.biglybt.android.client E/System:     DiskManagerImpl::filesExist::772, DiskManagerImpl::startSupport::558, DiskManagerImpl$6::runSupport::483, AERunnable::run::36, ThreadPool::runIt::336, ThreadPool$threadPoolWorker::run::742, AEThread2$threadWrapper::run::317
2020-08-09 19:19:56.914 757-2192/com.biglybt.android.client E/System: com.biglybt.core.diskmanager.cache.CacheFileManagerException: Failed to create parent directory '/storage/44363043-2d39-3630-4600-b2be679b46ab/Android/data/com.biglybt.android.client/files/blabla'
2020-08-09 19:19:56.915 757-2192/com.biglybt.android.client E/System:     at com.biglybt.core.diskmanager.cache.impl.CacheFileManagerImpl.rethrow(CacheFileManagerImpl.java:958)
2020-08-09 19:19:56.916 757-2192/com.biglybt.android.client E/System:     at com.biglybt.core.diskmanager.cache.impl.CacheFileManagerImpl.createFile(CacheFileManagerImpl.java:317)
2020-08-09 19:19:56.917 757-2192/com.biglybt.android.client E/System:     at com.biglybt.core.disk.impl.DiskManagerFileInfoImpl.<init>(DiskManagerFileInfoImpl.java:93)
2020-08-09 19:19:56.918 757-2192/com.biglybt.android.client E/System:     at com.biglybt.core.disk.impl.DiskManagerImpl.createFileInfo(DiskManagerImpl.java:923)
2020-08-09 19:19:56.919 757-2192/com.biglybt.android.client E/System:     at com.biglybt.core.disk.impl.DiskManagerImpl.filesExist(DiskManagerImpl.java:816)
2020-08-09 19:19:56.920 757-2192/com.biglybt.android.client E/System:     at com.biglybt.core.disk.impl.DiskManagerImpl.filesExist(DiskManagerImpl.java:772)
2020-08-09 19:19:56.921 757-2192/com.biglybt.android.client E/System:     at com.biglybt.core.disk.impl.DiskManagerImpl.startSupport(DiskManagerImpl.java:558)
2020-08-09 19:19:56.921 757-2192/com.biglybt.android.client E/System:     at com.biglybt.core.disk.impl.DiskManagerImpl$6.runSupport(DiskManagerImpl.java:483)
2020-08-09 19:19:56.922 757-2192/com.biglybt.android.client E/System:     at com.biglybt.core.util.AERunnable.run(AERunnable.java:36)
2020-08-09 19:19:56.922 757-2192/com.biglybt.android.client E/System:     at com.biglybt.core.util.ThreadPool.runIt(ThreadPool.java:336)
2020-08-09 19:19:56.923 757-2192/com.biglybt.android.client E/System:     at com.biglybt.core.util.ThreadPool$threadPoolWorker.run(ThreadPool.java:742)
2020-08-09 19:19:56.925 757-2192/com.biglybt.android.client E/System:     at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:317)
2020-08-09 19:19:56.927 757-2192/com.biglybt.android.client E/System: Caused by: com.biglybt.core.diskmanager.file.FMFileManagerException: Failed to create parent directory '/storage/44363043-2d39-3630-4600-b2be679b46ab/Android/data/com.biglybt.android.client/files/blabla'
2020-08-09 19:19:56.927 757-2192/com.biglybt.android.client E/System:     at com.biglybt.core.diskmanager.file.impl.FMFileImpl.createDirs(FMFileImpl.java:1119)
2020-08-09 19:19:56.928 757-2192/com.biglybt.android.client E/System:     at com.biglybt.core.diskmanager.file.impl.FMFileImpl.<init>(FMFileImpl.java:133)
2020-08-09 19:19:56.929 757-2192/com.biglybt.android.client E/System:     at com.biglybt.core.diskmanager.file.impl.FMFileLimited.<init>(FMFileLimited.java:51)
2020-08-09 19:19:56.930 757-2192/com.biglybt.android.client E/System:     at com.biglybt.core.diskmanager.file.impl.FMFileManagerImpl.createFile(FMFileManagerImpl.java:279)
2020-08-09 19:19:56.930 757-2192/com.biglybt.android.client E/System:     at com.biglybt.core.diskmanager.cache.impl.CacheFileManagerImpl.createFile(CacheFileManagerImpl.java:251)
2020-08-09 19:19:56.930 757-2192/com.biglybt.android.client E/System: 	... 10 more
```

I have tried debugging, but the issue seem disappear when I perform a step by step debugging.

My debug is done using the latest code downloaded 2 days ago.

**Comment by omarbelkhodja** [comment]
I found the problem comes from the following :

```java
if (FileUtil.mkdirs(parent)) {
    created_dirs = new_dirs;
    /*
    for (int i=created_dirs.size()-1;i>=0;i--){

        System.out.println( "created " + created_dirs.get(i));
    }
    */
} else {
    // had some reports of this exception being thrown when starting a torrent
    // double check in case there's some parallel creation being triggered somehow

    try {
        Thread.sleep(RandomUtils.nextInt(5000));
    } catch (Throwable e) {
    }
    FileUtil.mkdirs(parent);
    if (parent.isDirectory()) {
        created_dirs = new_dirs;
    } else {
        throw (new FMFileManagerException("Failed to create parent directory '" + parent + "'"));
    }
}
```

So the problem seems to be not really new...

**Comment by omarbelkhodja** [comment]
`FileUtil.mkdirs(parent)` -> is returning false

**Comment by TuxPaper** [comment]
hmm `/storage/44363043-2d39-3630-4600-b2be679b46ab/Android/data/com.biglybt.android.client/files/blabla` looks like the correct private external folder, so mkdir should work inside of it.  If the storage id (`443...`) or package name changed, it could be access to that folder has been lost.

On (most?) Android devices, the USB drive is read-only for normal `File` access, except for the per-app private folder. What makes it worse, is that `File.canWrite()` returns true for folders on the external drives, even though we can't write to it or create folders in it.  And this, as you found out, `mkdir` and `mkdirs` fails.

I'm currently working on full USB writing using Android's SAF.  This will require using the OS' folder selection app.  I'll add another comment when I've committed some changes (hopefully today or within the next few days).

If you are using the `BiglyBT-core-android.jar`, it's probably a bit out of date.  I'll put an updated one up today, along with a new xmwebui plugin that can handle SAF paths (`content://...`)

**Comment by omarbelkhodja** [comment]
I have recompiled BiglyBT-core-android.jar using a recent version, because the current main branch won't compile (new API used, not available in the compiler .jar).

Removing PLEX didn't really fix the issue. The issue is very random, changes whenever I restart the TV. My Android TV is not capable of formatting my USB Key as an internal storage. I'm formatting it as ExtFS, on my PC (128G, USB 3.1).

If you need help testing your new devs on Android's SAF, I'm interested to help !

**Comment by TuxPaper** [comment]
> I have recompiled BiglyBT-core-android.jar using a recent version, because the current main branch won't compile (new API used, not available in the compiler .jar).

Cool.  I hope you know that the android branch of core (https://github.com/BiglySoftware/BiglyBT/tree/android) has a working Maven config, so invoking `mvn clean package` produces a nice `BiglyBT-core-android.jar` to use.  In fact, that's exactly how I create a new jar to push to the Android project.

> Removing PLEX didn't really fix the issue. The issue is very random, changes whenever I restart the TV. My Android TV is not capable of formatting my USB Key as an internal storage. I'm formatting it as ExtFS, on my PC (128G, USB 3.1).

hmm, the storage id (44363043-2d39-3630-4600-b2be679b46ab) should be maintained across reboots, but you could always double check.


> If you need help testing your new devs on Android's SAF, I'm interested to help !

Always can use more testing!  Especially since each Android TV is "special" :/ I have a Bravia 2015 TV that doesn't have a SAF "Open Folder" dialog, which means no USB writing (except for that private external dir).  I also have access to a nVidia Shield, which shows the dialog, but you can't navigate it with the remote (Although if you have a mouse, it apparently works).

What's your Android TV, if you don't mind saying?

---

I've committed the code I was working on.  There's also a new xmwebui plugin (0.9.6) which can be downloaded using the `./updatePlugins.sh 2.4.0.1` command (or, if you have that as source code too, then you probably are already up to date)

**Comment by omarbelkhodja** [comment]
> Cool. I hope you know that the android branch of core (https://github.com/BiglySoftware/BiglyBT/tree/android) has a working Maven config, so invoking mvn clean package produces a nice BiglyBT-core-android.jar to use. In fact, that's exactly how I create a new jar to push to the Android project.

Actually what I did is a copy/paste from BiglyBT repository into the core directory, then I compiled using gradle. After that I renamed the `core.jar` into `BiglyBT-core-android.jar`

> What's your Android TV, if you don't mind saying?
My TV is a Sony Bravia 2016 (KD-49X8000D), with Android 8.0.0, and a Kernel 3.10.79 (June 2019). I will update the source code today and perform a few tests.

Thanks !

**Comment by omarbelkhodja** [comment]
Tested now : I can see a new button "Browse". When I click on it, I have the following exception :
```
2020-08-12 09:43:57.221 8067-8067/com.biglybt.android.client E/InputEventReceiver: Exception dispatching input event.
2020-08-12 09:43:57.221 8067-8067/com.biglybt.android.client E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
2020-08-12 09:43:57.231 8067-8067/com.biglybt.android.client E/MessageQueue-JNI: java.lang.NullPointerException: Null initialDirectory
        at net.rdrei.android.dirchooser.AutoParcel_DirectoryChooserConfig.<init>(AutoParcel_DirectoryChooserConfig.java:23)
        at net.rdrei.android.dirchooser.AutoParcel_DirectoryChooserConfig.<init>(AutoParcel_DirectoryChooserConfig.java:6)
        at net.rdrei.android.dirchooser.AutoParcel_DirectoryChooserConfig$Builder.build(AutoParcel_DirectoryChooserConfig.java:171)
        at com.biglybt.android.util.FileUtils.buildOpenFolderChooserIntent(FileUtils.java:174)
        at com.biglybt.android.util.FileUtils.openFolderChooser(FileUtils.java:192)
        at com.biglybt.android.client.dialog.DialogFragmentAbstractLocationPicker.lambda$onCreateDialog$2$DialogFragmentAbstractLocationPicker(DialogFragmentAbstractLocationPicker.java:152)
        at com.biglybt.android.client.dialog.-$$Lambda$DialogFragmentAbstractLocationPicker$ncrqhCCEvYSEc83KXAEZ6YwVvpU.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:6256)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:992)
        at android.view.View.onKeyUp(View.java:12415)
        at android.widget.TextView.onKeyUp(TextView.java:7420)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2715)
        at android.view.View.dispatchKeyEvent(View.java:11658)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:437)
        at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1818)
        at androidx.core.view.KeyEventDispatcher.dialogSuperDispatchKeyEventPre28(KeyEventDispatcher.java:166)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:89)
        at androidx.appcompat.app.AppCompatDialog.dispatchKeyEvent(AppCompatDialog.java:214)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3051)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:351)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4725)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4597)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4139)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4192)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4158)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4285)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4166)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4342)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4139)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4192)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4158)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4166)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4139)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4192)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4158)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4285)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4166)
    	at android.view.ViewRoo
2020-08-12 09:43:57.232 8067-8067/com.biglybt.android.client D/AndroidRuntime: Shutting down VM
2020-08-12 09:43:57.241 8067-8067/com.biglybt.android.client E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.biglybt.android.client, PID: 8067
    java.lang.NullPointerException: Null initialDirectory
        at net.rdrei.android.dirchooser.AutoParcel_DirectoryChooserConfig.<init>(AutoParcel_DirectoryChooserConfig.java:23)
        at net.rdrei.android.dirchooser.AutoParcel_DirectoryChooserConfig.<init>(AutoParcel_DirectoryChooserConfig.java:6)
        at net.rdrei.android.dirchooser.AutoParcel_DirectoryChooserConfig$Builder.build(AutoParcel_DirectoryChooserConfig.java:171)
        at com.biglybt.android.util.FileUtils.buildOpenFolderChooserIntent(FileUtils.java:174)
        at com.biglybt.android.util.FileUtils.openFolderChooser(FileUtils.java:192)
        at com.biglybt.android.client.dialog.DialogFragmentAbstractLocationPicker.lambda$onCreateDialog$2$DialogFragmentAbstractLocationPicker(DialogFragmentAbstractLocationPicker.java:152)
        at com.biglybt.android.client.dialog.-$$Lambda$DialogFragmentAbstractLocationPicker$ncrqhCCEvYSEc83KXAEZ6YwVvpU.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:6256)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:992)
        at android.view.View.onKeyUp(View.java:12415)
        at android.widget.TextView.onKeyUp(TextView.java:7420)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2715)
        at android.view.View.dispatchKeyEvent(View.java:11658)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:437)
        at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1818)
        at androidx.core.view.KeyEventDispatcher.dialogSuperDispatchKeyEventPre28(KeyEventDispatcher.java:166)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:89)
        at androidx.appcompat.app.AppCompatDialog.dispatchKeyEvent(AppCompatDialog.java:214)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3051)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:351)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4725)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4597)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4139)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4192)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4158)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4285)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4166)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4342)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4139)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4192)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4158)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4166)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4139)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4192)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4158)
2020-08-12 09:43:57.245 8067-8067/com.biglybt.android.client E/AndroidRuntime:     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4285)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4166)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4342)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4139)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4192)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4158)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4166)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4139)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4192)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4158)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4285)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4166)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4342)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4139)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6653)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6627)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6588)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6756)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:142)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
2020-08-12 09:43:57.251 8067-8067/com.biglybt.android.client E/CRASH: [*main] NullPointerException: Null initialDirectory: <init>@AutoParcel_DirectoryChooserConfig:23, <init>@AutoParcel_DirectoryChooserConfig:6, $Builder.build@AutoParcel_DirectoryChooserConfig:171, buildOpenFolderChooserIntent@FileUtils:174, openFolderChooser@FileUtils:192, lambda$onCreateDialog$2$DialogFragmentAbstractLocationPicker@DialogFragmentAbstractLocationPicker:152, -$$Lambda$DialogFragmentAbstractLocationPicker$ncrqhCCEvYSEc83KXAEZ6YwVvpU.onClick:2, performClick@View:6256, performClick@MaterialButton:992, onKeyUp@View:12415, onKeyUp@TextView:7420, dispatch@KeyEvent:2715
2020-08-12 09:43:57.264 8067-8067/com.biglybt.android.client D/ATbare: {"commands":[{"listener-id":"android","op-id":"crash","seq-id":1,"values":{"android-version":26,"app-version":1029999,"client-type":"Core","client-version":"2.4.0.1_CVS","device-name":"Sony: BRAVIA 4K GB","device-type":"TV","exception-name":"NullPointerException: Null initialDirectory","is-crash":1,"locale":"fr_FR","rpc-version":"16/8","screen-density":320,"screen-inches":48.29745357204145,"stack":"<init>@AutoParcel_DirectoryChooserConfig:23, <init>@AutoParcel_DirectoryChooserConfig:6, $Builder.build@AutoParcel_DirectoryChooserConfig:171, buildOpenFolderChooserIntent@FileUtils:174, openFolderChooser@FileUtils:192, lambda$onCreateDialog$2$DialogFragmentAbstractLocationPicker@DialogFragmentAbstractLocationPicker:152, -$$Lambda$DialogFragmentAbstractLocationPicker$ncrqhCCEvYSEc83KXAEZ6YwVvpU.onClick:2, performClick@View:6256, performClick@MaterialButton:992, onKeyUp@View:12415, onKeyUp@TextView:7420, dispatch@KeyEvent:2715","thread":"*main","v":"DialogFragmentLocationPicker/SettingsActivity"}}]}
2020-08-12 09:43:58.089 8067-8067/com.biglybt.android.client D/ATbare: Sync Response: {"replies":[{"seq-id":1}]}
2020-08-12 09:43:58.157 8067-8074/? I/zygote: Debugger is no longer active`

**Comment by TuxPaper** [comment]
> Tested now : I can see a new button "Browse". When I click on it, I have the following exception :
> 
> ```
> 2020-08-12 09:43:57.231 8067-8067/com.biglybt.android.client E/MessageQueue-JNI: java.lang.NullPointerException: Null initialDirectory
>         at net.rdrei.android.dirchooser.AutoParcel_DirectoryChooserConfig.<init>(AutoParcel_DirectoryChooserConfig.java:23)
>         at net.rdrei.android.dirchooser.AutoParcel_DirectoryChooserConfig.<init>(AutoParcel_DirectoryChooserConfig.java:6)
>         at net.rdrei.android.dirchooser.AutoParcel_DirectoryChooserConfig$Builder.build(AutoParcel_DirectoryChooserConfig.java:171)
>         at com.biglybt.android.util.FileUtils.buildOpenFolderChooserIntent(FileUtils.java:174)

Check to make sure your up to date, your line numbers are off and there's a null check in that method https://github.com/BiglySoftware/BiglyBT-Android/blob/master/BiglyBT/src/main/java/com/biglybt/android/util/FileUtils.java#L158

**Comment by TuxPaper** [comment]
v1.3.0.2 is out with SAF support.  There's probably enough changes that it would make sense to create a new github issue about it if/when you find one.  So, I'll close this issue up.

Thanks for the report, the debugging and the help.  Appreciate it, "bigly"!
